#!/usr/bin/env python3
"""Procedurally synthesises all Wall Breach sound effects (no external assets).
Writes WAV files, then converts to OGG Vorbis with ffmpeg if available."""
import numpy as np, wave, os, subprocess, sys
SR = 44100
# Output goes to app/src/main/assets/audio/ (git-ignored; regenerated by bootstrap.sh and CI).
OUT = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "assets", "audio")
os.makedirs(OUT, exist_ok=True)
rng = np.random.default_rng(7)

def t(d): return np.linspace(0, d, int(SR * d), endpoint=False)
def env(n, a=0.005, r=None):
    e = np.ones(n); na = max(1, int(a * SR)); e[:na] = np.linspace(0, 1, na)
    r = n - na if r is None else int(r * SR)
    e[-r:] *= np.linspace(1, 0, r) ** 2
    return e
def sweep(f0, f1, d, shape="sin"):
    f = np.geomspace(f0, f1, int(SR * d)); ph = 2 * np.pi * np.cumsum(f) / SR
    return np.sin(ph) if shape == "sin" else np.sign(np.sin(ph)) * 0.6
def noise(d): return rng.uniform(-1, 1, int(SR * d))
def lowpass(x, k):
    k = max(1, int(k)); return np.convolve(x, np.ones(k) / k, mode="same")

def save(name, x):
    x = x / (np.max(np.abs(x)) + 1e-9) * 0.9
    pcm = (x * 32767).astype(np.int16)
    p = os.path.join(OUT, name + ".wav")
    with wave.open(p, "wb") as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(SR); w.writeframes(pcm.tobytes())
    ogg = os.path.join(OUT, name + ".ogg")
    try:
        subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", p, "-c:a", "libvorbis", "-q:a", "4", ogg], check=True)
        os.remove(p)
    except Exception as e:
        print("ffmpeg failed, keeping wav:", e, file=sys.stderr)

d = 0.18; save("laser", (sweep(1800, 300, d) * 0.7 + sweep(2400, 500, d, "sq") * 0.3) * env(int(SR*d), r=0.15))
d = 0.6; n = noise(d); save("explode", (lowpass(n, 6) * 0.7 + sweep(160, 40, d) * 0.6) * env(int(SR*d), a=0.002, r=0.55))
d = 1.6; n = noise(d); save("boss_explode", (lowpass(n, 10) + sweep(120, 25, d) * 0.8) * env(int(SR*d), a=0.002, r=1.5))
d = 0.35; save("hurt", (sweep(220, 80, d, "sq") + lowpass(noise(d), 3) * 0.4) * env(int(SR*d), r=0.3))
d = 0.22; save("shield", (np.sin(2*np.pi*880*t(d)) * 0.5 + np.sin(2*np.pi*1320*t(d)) * 0.4 + noise(d)*0.1) * env(int(SR*d), a=0.001, r=0.2))
d = 1.2; tt = t(d); save("portal", (np.sin(2*np.pi*(90 + 40*np.sin(2*np.pi*3*tt))*tt) * 0.6 + lowpass(noise(d), 40) * 0.6) * env(int(SR*d), a=0.3, r=0.6))
d = 0.25; save("enemy_shot", sweep(600, 900, d) * env(int(SR*d), r=0.2) * (0.6 + 0.4*np.sin(2*np.pi*40*t(d))))
d = 0.9; save("wave", np.concatenate([np.sin(2*np.pi*f*t(0.15)) * env(int(SR*0.15)) for f in (523, 659, 784, 1047)] + [np.zeros(int(SR*0.3))]))
d = 2.0; tt = t(d); save("boss_alarm", np.sign(np.sin(2*np.pi*(300 + 150*np.sign(np.sin(2*np.pi*2*tt)))*tt)) * 0.5 * env(int(SR*d), a=0.01, r=0.3))
d = 1.5; save("gameover", np.concatenate([sweep(f, f*0.7, 0.35, "sq") * env(int(SR*0.35)) for f in (440, 370, 311, 220)]) )
d = 0.08; save("click", np.sin(2*np.pi*1500*t(d)) * env(int(SR*d), a=0.001, r=0.07))
d = 0.3; save("reflect", (sweep(500, 2500, d) + sweep(750, 3000, d)*0.5) * env(int(SR*d), r=0.25))
print(sorted(os.listdir(OUT)))
